import { defineConfig } from 'vitepress';

// https://vitepress.dev/reference/site-config
export default defineConfig({
  lang: 'en-US',
  title: 'MCP RAG Server',
  description:
    'MCP server providing Retrieval Augmented Generation capabilities.',
  lastUpdated: true,
  cleanUrls: true,

  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    // logo: '/logo.svg', // Optional
    siteTitle: 'MCP RAG Server',

    nav: [
      { text: 'Guide', link: '/guide/introduction', activeMatch: '/guide/' },
      { text: 'API Reference', link: '/api/', activeMatch: '/api/' },
      // Add other top-level sections if needed
    ],

    sidebar: {
      '/guide/': [
        {
          text: 'Guide',
          items: [
            { text: 'Introduction', link: '/guide/introduction' },
            { text: 'Installation', link: '/guide/installation' },
            { text: 'Getting Started', link: '/guide/getting-started' },
            // Add more guide pages later
          ],
        },
      ],
      '/api/': [
        // Sidebar for API docs - auto-generated by TypeDoc
        { text: 'API Home', link: '/api/' },
        // Links to modules/classes will be generated
      ],
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/sylphlab/rag-server-mcp' },
    ],

    editLink: {
      pattern:
        'https://github.com/sylphlab/rag-server-mcp/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },

    footer: {
      message: 'Released under the MIT License.',
      copyright: `Copyright © ${new Date().getFullYear()} Sylph Lab`, // Updated owner name
    },

    // Optional: Algolia search
    // search: {
    //   provider: 'algolia',
    //   options: {
    //     appId: '...',
    //     apiKey: '...',
    //     indexName: '...'
    //   }
    // }
  },

  // Optional: Markdown configuration
  markdown: {
    lineNumbers: true,
  },
});
